# Site settings
title: Dadeon
subtitle: "Musings on datums"
description: "Musings on datums"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dadeon.com" # the base hostname & protocol for your site

author1: "Jonathan Mortensen"
email1: jonathan@mortensens.us
twitter_username1: jmomort
github_username1:  jmomort
site1: jonathanmortensen.com 

author2: "Francisco Gimenez"
email2: francisco@catenus.com
twitter_username2: fjeg1987
github_username2:  fjeg
site2: catenus.com

# Build settings
markdown: kramdown

collections:
      optibeard:
              output: true
              #permalink: /optibeard/:title
      data-integration:
              output: true
              #permalink: /data-integration/:title
      jmo:
              output: true
              #permalink: /:title
              author: "Jonathan Mortensen"
